### ISSUE TITLE
Aerosol data

### ISSUE THREAD

**Issue by atillmanns** [bcgov/pahwq#12]
I checked in with the air quality science specialist and he suggests using VIIRS data (https://www.star.nesdis.noaa.gov/atmospheric-composition-training/python_viirs_level3_download.php) as this is spatially expansive and more up to date than the NEO data.

**Comment by ateucher** [comment]
Thanks @atillmanns for checking. I did switch to using MODIS/Aqua from NEO for the aerosol data (see #8). It has data as of early Nov 2023 so I should think that should be up to date enough, especially since we want to capture typical conditions rather than a specific point in time - so monthly averages are likely appropriate? I did a quick search on MODIS vs VIIRS and it seems they are comparable in both coverage and accuracy (e.g., https://www.frontiersin.org/articles/10.3389/fenvs.2023.1158641/full, https://www.sciencedirect.com/science/article/abs/pii/S1352231021006063). VIIRS has a higher spatial resolution (750m vs 10km I think), but I don't think that level of accuracy is required, and it greatly increases the computation time to process the data to fit into the package. 

I can switch to VIIRS if necessary, but I'm not sure of the gains it will bring.

**Comment by atillmanns** [comment]
Let's leave it as NEO.  Thanks for your research on this topic!  And yes, monthly averages over the past 20 years or so would be great.

**Comment by ateucher** [comment]
Thanks @atillmanns! Sounds good - if the sensitivity analysis shows it's really important maybe we can think about revisiting it?

**Comment by atillmanns** [comment]
@ateucher yes, that makes sense.
